virtual_zoo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('zoo_app.urls')),


]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

zoo_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index),
    path('index', views.index_redir),

    path('register', views.register),
    path('register_exe', views.register_exe),
    path('logout', views.logout),
    path('login', views.login),
    path('login_exe', views.login_exe),
    path('edit_user', views.edit_user),
    path('edit_user_exe', views.edit_user_exe),
    
    path('contribute', views.contribute),

    path('animals/<int:render_id>', views.animal),
    path('families/<int:render_id>', views.family),
    path('aniclasses/<int:render_id>', views.aniclass),
    path('biomes/<int:render_id>', views.biome),
    path('users/<int:render_id>', views.user_profile),

    path('add_biome', views.add_biome),
    path('add_biome_exe', views.add_biome_exe),
    path('add_class', views.add_class),
    path('add_class_exe', views.add_class_exe),
    path('add_family', views.add_family),
    path('add_family_exe', views.add_family_exe),
    path('add_animal', views.add_animal),
    path('add_animal_exe', views.add_animal_exe),

    path('comment', views.comment),

    path('families/<int:render_id>/edit', views.edit_family),
    path('edit_family_exe', views.edit_family_exe),
    path('aniclasses/<int:render_id>/edit', views.edit_aniclass),
    path('edit_aniclass_exe', views.edit_aniclass_exe),
    path('biomes/<int:render_id>/edit', views.edit_biome),
    path('edit_biome_exe', views.edit_biome_exe),
    path('animals/<int:render_id>/edit', views.edit_animal),
    path('edit_animal_exe', views.edit_animal_exe),
]

zoo_app/models.py
from django.db import models
import re	# the regex module
import bcrypt
EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
# Create your models here.

class Aniclass(models.Model):
    name = models.CharField(max_length=40)
    desc = models.CharField(max_length=500)
    img = models.ImageField(upload_to ='images/')


    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
#    objects = UserManager()
    def __str__(self):
        return f"{self.name}"

class Family(models.Model):
    name = models.CharField(max_length=40)
    aniclass = models.ForeignKey(Aniclass, related_name="families", on_delete = models.CASCADE)
    desc = models.CharField(max_length=500)
    img = models.ImageField(upload_to ='images/')


    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
#    objects = UserManager()
    def __str__(self):
        return f"{self.name}"

class Animal(models.Model):
    name = models.CharField(max_length=40)
    family = models.ForeignKey(Family, related_name="animals", on_delete = models.CASCADE)
    aniclass = models.ForeignKey(Aniclass, related_name="animals", on_delete = models.CASCADE)
    desc = models.CharField(max_length=500)
    face_img = models.ImageField(upload_to ='images/')
    wide_img = models.ImageField(upload_to ='images/')


    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
#    objects = UserManager()
    def __str__(self):
        return f"{self.name}"






class Biome(models.Model):
    name = models.CharField(max_length=40)
    animals = models.ManyToManyField(Animal, related_name="biome")
    desc = models.TextField(max_length=500)
    img = models.ImageField(upload_to ='images/')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
#    objects = UserManager()
    def __str__(self):
        return f"{self.name}"



    
class UserManager(models.Manager):
    def basic_validator(self, postData):
        errors = {}
        users = self.filter(email=postData['email'])
        handle = self.filter(handle=postData['handle'])
        if users:
            errors["email"] = "Email already in use"
        if handle:
            errors["handle"] = "Handle already in use"
        if postData['pwd'] != postData['confirm']:
            errors["password"] = "Passwords do not match"
        if len(postData['first_name']) < 2:
            errors["first_name"] = "First name must be at least 2 characters"
        if len(postData['last_name']) < 2:
            errors["last_name"] = "Last name must be at least 2 characters"
        if len(postData['handle']) < 2:
            errors["handle"] = "Handle must be at least 2 characters"
        

        if not EMAIL_REGEX.match(postData['email']): 
            errors['email'] = "Invalid email address!"
        
        return errors
    def authenticate(self, email, password):
        users = self.filter(email=email)
        if not users:
            return False
        user = users[0]
        return bcrypt.checkpw(password.encode(), user.pwdhash.encode())

    def update_validator(self, first_name, last_name, old_handle, new_handle, old_email, new_email):
        errors = {}
        if old_handle != new_handle:
            handle_check = self.filter(handle= new_handle)
        else:
            handle_check = {}
        if old_email != new_email:
            email_check = self.filter(email= new_email)
        else:
            email_check = {}
        
        
        if email_check:
            errors["email"] = "New email already in use"
        if handle_check:
            errors["handle"] = "New handle already in use"
        if len(first_name) < 2:
            errors["first_name"] = "First name must be at least 2 characters"
        if len(last_name) < 2:
            errors["last_name"] = "Last name must be at least 2 characters"
        if len(new_handle) < 2:
            errors["handle"] = "Handle must be at least 2 characters"
        

        if not EMAIL_REGEX.match(new_email): 
            errors['email'] = "Invalid email address!"
        
        return errors

class User(models.Model):
    first_name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    handle = models.CharField(max_length=40)
    email = models.CharField(max_length=255)
    pwdhash = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()
    def __str__(self):
        return f"{self.first_name}"

class Edit(models.Model):
    text = models.TextField(max_length=50)
    editor = models.ForeignKey(User, related_name="edits", on_delete = models.CASCADE)
    bedit = models.ForeignKey(Biome, related_name="edits", null=True, on_delete = models.CASCADE)
    cedit = models.ForeignKey(Aniclass, related_name="edits", null=True, on_delete = models.CASCADE)
    fedit = models.ForeignKey(Family, related_name="edits", null=True, on_delete = models.CASCADE)
    aedit = models.ForeignKey(Animal, related_name="edits", null=True, on_delete = models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"Edit: {self.editor} {self.created_at}"

class Comment(models.Model):
    text = models.TextField(max_length=50)
    commentor = models.ForeignKey(User, related_name="comments", on_delete = models.CASCADE)
    bcomment = models.ForeignKey(Biome, related_name="comments", null=True, on_delete = models.CASCADE)
    ccomment = models.ForeignKey(Aniclass, related_name="comments", null=True, on_delete = models.CASCADE)
    fcomment = models.ForeignKey(Family, related_name="comments", null=True, on_delete = models.CASCADE)
    acomment = models.ForeignKey(Animal, related_name="comments", null=True, on_delete = models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"Comment: {self.commentor} {self.created_at}"

zoo_app/forms.py
from django import forms



class Testform(forms.Form):
    name = forms.CharField()
    img = forms.ImageField()

zoo_app/templates/add_biome.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Add Habitat</title>
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>

  <body>
  <div class="container">
    {% include 'partials/nav.html'%}
    <div class="row p-1">
      <div class="col-12 mb-1 skyblue border border-dark rounded">
      <h1>Add Habitat</h1>
      <form method="POST" enctype="multipart/form-data" action="/add_biome_exe">
      {% csrf_token %}
      <p>
        <label for="id_name">Name:</label>
        <input type="text" name="name" required id="id_name" />
      </p>
      <p>Description:
        <textarea name="desc"></textarea>
        <input
          type="hidden"
          id="aniclass_id"
          name="aniclass_id"
          value="{{aniclass.id}}"
        />
      </p>
      <p>
        <label for="id_img">Img:</label>
        <input type="file" name="img" accept="image/*" required id="id_img" />
      </p>
      <input type="submit" value="Submit" />
    </form>
    </div>
  </div>
  </div>
  </body>
</html>

zoo_app/templates/add_class.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Add Animal Class</title>
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>

  <body>
  <div class="container">
    {% include 'partials/nav.html'%}

    <div class="row p-1">
      <div class="col-12 mb-1 skyblue border border-dark rounded">
      <h1>Add Animal Class</h1>
      <form method="POST" enctype="multipart/form-data" action="/add_class_exe">
      {% csrf_token %}
      <p>
        <label for="id_name">Animal Class:</label>
        <input type="text" name="name" required id="id_name" />
      </p>
      <p>
        <label for="id_desc">Description:</label>
        <textarea name="desc"></textarea>
      </p>
      <p>
        <label for="id_img">Img:</label>
        <input type="file" name="img" accept="image/*" required id="id_img" />
      </p>
      <input type="submit" value="Submit" />
      </form>
      </div>
    </div>
  </div>
  </body>
</html>

zoo_app/templates/add_family.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Add Animal Family</title>
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>

  <body>
  <div class="container">
    {% include 'partials/nav.html'%}

    <div class="row p-1">
      <div class="col-12 mb-1 skyblue border border-dark rounded">
      <h1>Add Family</h1>
      <form method="POST" enctype="multipart/form-data" action="/add_family_exe">
      {% csrf_token %}
      <p>
        <label for="id_name">Animal Family:</label>
        <input type="text" name="name" required id="id_name" />
      </p>
      <p>
        Description:
        <textarea name="desc"></textarea>
      </p>
      <p>
        <label for="id_img">Img:</label>
        <input type="file" name="img" accept="image/*" required id="id_img" />
      </p>
      <label for="class_id">Class:</label>
      <select name="class" id="class_id">
        {% for class in all_classes %}
        <option value="{{class.id}}">{{class.name}}</option>
        {% endfor %}
      </select>
      <input type="submit" value="Submit" />
      </form>
      </div>
    </div>
  </div>
  </body>
</html>

zoo_app/templates/edit_aniclass.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Edit Animal Class</title>
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  
  </head>
  
  <body>
  <div class="container">
    {% include 'partials/nav.html'%}

    <div class="row p-1">
      <div class="col-12 col-lg-5 border border-dark rounded skyblue p-2">
      <h3>{{aniclass.name}}</h3>
      <img class="face" src="{{aniclass.img.url}}" />

      <div class="animal_description">
        <h4>Quick Description</h4>
        <p>
          <b>{{aniclass.desc}}</b>
        </p>
      </div>
      </div>
      <div class="col-12 col-lg-5 border border-dark rounded skyblue p-2">
        <h1>Edit Text</h1>
        <form action="/edit_aniclass_exe" method="POST">
          {% csrf_token %}
          <p>
            <label for="id_name">Animal Class:</label>
            <input
              type="text"
              name="name"
              required
              id="id_name"
              value="{{aniclass.name}}"
            />
          </p>
          <p>Description:</p>
          <textarea name="desc">{{aniclass.desc}}</textarea>
          <input
            type="hidden"
            id="aniclass_id"
            name="aniclass_id"
            value="{{aniclass.id}}"
          />
          <input type="submit" value="Submit" />
        </form>
        <h1>Edit Image</h1>
      <form
        action="/edit_aniclass_exe"
        enctype="multipart/form-data"
        method="POST"
      >
        {% csrf_token %}
        <p>
          <input type="file" name="img" accept="image/*" required id="id_img" />
          <input type="submit" value="Submit" />
        </p>
        <input
          type="hidden"
          id="aniclass_id"
          name="aniclass_id"
          value="{{aniclass.id}}"
        />
      </form>
      </div>

    </div>

    

  </div>
  </body>
</html>

zoo_app/templates/edit_animal.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Show Animal</title>
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body>
  <div class="container">
    {% include 'partials/nav.html'%}

    <div class="row p-1">
      <div class="col-12 col-lg-5 border border-dark rounded skyblue p-2" style="background-image: url({{biome.img.url}})">
        <div class="row">
          <div class="col-6">
          <img class="face" src="{{animal.face_img.url}}" />
          </div>
  
          <div class="col-5 skyblue border border-dark rounded p-2">
          <h5>{{animal.name}}</h5>
          <h5>Family: <a href="/families/{{animal.family.id}}">{{animal.family}}</a></h5>
          <h5>Class: <a href="/aniclasses/{{animal.aniclass.id}}">{{animal.aniclass}}</a></h5>
          <h5>Habitats: 
            {% for biome in existing_biomes %}
            <a href="/biomes/{{biome.id}}">{{biome.name}}</a>
           
            {% endfor %}
            </h5>
  
          
          </div>
        </div>
        <div class="row d-flex justify-content-around p-1">
        <div class="col-11 border border-dark rounded skyblue p-2">
          <p>
            <b>{{animal.desc}}</b>
          </p>
        </div>
        </div>
        <img src="{{animal.wide_img.url}}" class="wideshot" />
      </div>
  
      <div class="col-12 col-lg-6 border border-dark rounded skyblue p-2">
          <h1>Edit Text</h1>
          <form action="/edit_animal_exe" method="POST">
            {% csrf_token %}
            <p>
              <label for="id_name">Animal Name:</label>
              <input
                type="text"
                name="name"
                required
                id="id_name"
                value="{{animal.name}}"
              />
            </p>
            <p>Description:</p>
            <textarea name="desc">{{animal.desc}}</textarea>
            <input
              type="hidden"
              id="animal_id"
              name="animal_id"
              value="{{animal.id}}"
            />
            <input type="submit" value="Submit" />
          </form>
          <form action="/edit_animal_exe" method="POST">
            {% csrf_token %}
            
              <label for="biome_id">Add Habitat:</label>
              <select name="biome" id="biome_id">
                {% for biome in potential_biomes %}
                <option value="{{biome.id}}">{{biome.name}}</option>
                {% endfor %}
              </select>
              <input
                type="hidden"
                id="animal_id"
                name="animal_id"
                value="{{animal.id}}"
              />
            
            <input type="submit" value="Submit" />
          </form>
          <form action="/edit_animal_exe" method="POST">
            {% csrf_token %}
            
              <label for="kill_biome_id">Remove Habitat:</label>
              <select name="kill_biome" id="kill_biome_id">
                {% for biome in existing_biomes %}
                <option value="{{biome.id}}">{{biome.name}}</option>
                {% endfor %}
              </select>
              <input
                type="hidden"
                id="animal_id"
                name="animal_id"
                value="{{animal.id}}"
              />
            
            <input type="submit" value="Submit" />
          </form>
          <h1>Edit Face Image</h1>
      <form
        action="/edit_animal_exe"
        enctype="multipart/form-data"
        method="POST"
      >
        {% csrf_token %}
        <p>
          <input type="file" name="face_img" accept="image/*" required id="id_face_img" />
          <input type="submit" value="Submit" />
        </p>
        <input
          type="hidden"
          id="animal_id"
          name="animal_id"
          value="{{animal.id}}"
        />
      </form>
      <h1>Edit Wide Image</h1>
      <form
        action="/edit_animal_exe"
        enctype="multipart/form-data"
        method="POST"
      >
        {% csrf_token %}
        <p>
          <input type="file" name="wide_img" accept="image/*" required id="wide_id_img" />
          <input type="submit" value="Submit" />
        </p>
        <input
          type="hidden"
          id="animal_id"
          name="animal_id"
          value="{{animal.id}}"
        />
      </form>
        
      </div>
  
    </div>
    


    

  </div>
  </body>
</html>

zoo_app/templates/edit_biome.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Show Animal</title>
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body>
  <div class="container">
    {% include 'partials/nav.html'%}
    <div class="row p-1">
      <div class="col-12 col-lg-5 border border-dark rounded p-2" style="background-image: url({{biome.img.url}})">
        
        <div class="row p-3">
        <div class="col-12 skyblue border border-dark rounded p-2">
          <h3>{{biome.name}}</h3>
          <p><b>{{biome.desc}}</b></p>
        </div>
        </div>
      </div>
      <div class="col-12 col-lg-5 border border-dark rounded skyblue p-2">
        <h1>Edit Text</h1>
        <form action="/edit_biome_exe" method="POST">
        {% csrf_token %}
        <p>
          <label for="id_name">Habitat Name:</label>
          <input
            type="text"
            name="name"
            required
            id="id_name"
            value="{{biome.name}}"
          />
        </p>
        <p>Description:</p>
        <textarea name="desc">{{biome.desc}}</textarea>
        <input
          type="hidden"
          id="biome_id"
          name="biome_id"
          value="{{biome.id}}"
        />
        <input type="submit" value="Submit" />
        </form>
        <h1>Edit Image</h1>
      <form
        action="/edit_biome_exe"
        enctype="multipart/form-data"
        method="POST"
      >
        {% csrf_token %}
        <p>
          <input type="file" name="img" accept="image/*" required id="id_img" />
          <input type="submit" value="Submit" />
        </p>
        <input
          type="hidden"
          id="biome_id"
          name="biome_id"
          value="{{biome.id}}"
        />
      </form>
      </div>
    </div>



 

  </div>
  </body>
</html>